
// BibTeX 数据库 - 在这里管理所有论文的引用数据
const bibDatabase = {
    'Sun2024-TSC': `@article{Sun2024-TSC,
abstract = {Multi-cloud is a promising paradigm due to its advantages such as avoiding vendor lock-in and optimising costs. This paper focuses on dynamic flexible workflow scheduling with minimum total monetary cost in multi-clouds, considering multiple categories of services for each cloud with different configurations and billing methods. Existing studies generally ignore the characteristics and states of each individual cloud when making schedules, which may be ineffective regarding cost savings and quality of service. To address this issue, we propose to introduce a cloud selection decision on top of the existing task selection and resource selection decisions to help us select appropriate resource for task in an overall cost-effective cloud. To automatically learn the task, cloud and resource selection rules simultaneously, we propose a new genetic programming with multi-tree representation based on a customised discrete event-driven dynamic workflow scheduling simulator. Simulation results based on two real-world data traces show that the proposed algorithm performs significantly better than the state-of-the-art algorithms in terms of reducing the rental costs and deadline deviation, and improving the success rate. The results also show that the superiority of the proposed algorithm lies in the ability to select an appropriate cloud resource for a task.},
author = {Sun, Zaixing and Mei, Yi and Zhang, Fangfang and Huang, Hejiao and Gu, Chonglin and Zhang, Mengjie},
doi = {10.1109/TSC.2024.3394691},
issn = {1939-1374},
journal = {IEEE Transactions on Services Computing},
keywords = {Cloud computing,Costs,Dynamic scheduling,Dynamic workflow scheduling,Genetic programming,Heuristic algorithms,Processor scheduling,Task analysis,deadline constraint,genetic programming,hyper-heuristic,multi-clouds},
month = {sep},
number = {5},
pages = {2687--2703},
title = {{Multi-Tree Genetic Programming Hyper-Heuristic for Dynamic Flexible Workflow Scheduling in Multi-Clouds}},
url = {https://ieeexplore.ieee.org/document/10509784/},
volume = {17},
year = {2024}
}`,

    'Sun2023-ESWA': `@article{Sun2023-ESWA,
abstract = {Benefiting from the flexible, scalable and secure environment, hybrid cloud can overcome the shortage of limited resources in private cloud to simultaneously execute large-scale scientific workflows. In hybrid cloud, privacy-sensitive tasks are not allowed to be executed on public resources, while non-sensitive tasks are unrestricted. As an NP-Complete problem, it is extraordinarily challenging to schedule multiple workflows efficiently, economically and energy-savingly under quality-of-service constraints. This paper models the hybrid-cloud-based privacy-aware multi-workflow scheduling as a tri-objective optimization problem that optimizes workflow-oriented total tardiness, private-cloud-oriented total energy consumption, and public-cloud-oriented total monetary cost. To the best of authors' knowledge, few studies have been conducted on the tri-objective privacy-aware multi-workflow scheduling in hybrid cloud (PMWS-HC). To solve this problem, we dissect various factors involved during task scheduling and devise a novel Heuristic Scheduling Algorithm based on 9 Factors (HSA9Fs), which dynamically selects the workflows and tasks to be scheduled, and the corresponding VMs to execute them. To optimize the three conflicting objectives simultaneously, we propose a nested algorithm called MSIA, which first employs a Multi-objective Salp swarm algorithm to explore for the Pareto solutions, and then uses an Iterative greedy Algorithm to perform a refined search on individuals to obtain high-quality solutions. Extensive Medium-Small-Scale and Large-Scale simulation experiments show that both HSA9Fs and MSIA outperform state-of-the-art scheduling algorithms in several multi-objective performance metrics.},
author = {Sun, Zaixing and Huang, Hejiao and Li, Zhikai and Gu, Chonglin and Xie, Ruitao and Qian, Bin},
doi = {10.1016/j.eswa.2023.120401},
issn = {09574174},
journal = {Expert Systems with Applications},
keywords = {Directed acyclic graph,Heuristic algorithm,Hybrid cloud,Multi-objective optimization,Multi-workflow scheduling,Pareto front},
mendeley-groups = {bib,multiple clouds},
month = {oct},
pages = {120401},
title = {{Efficient, economical and energy-saving multi-workflow scheduling in hybrid cloud}},
url = {https://linkinghub.elsevier.com/retrieve/pii/S095741742300903X},
volume = {228},
year = {2023}
}`,

    'Sun2022-TSC': `@article{Sun2022-TSC,
abstract = {Cloud computing is an emerging computational infrastructure for cost-efficient workflow execution that provides flexible and dynamically scalable computing resources at pay-as-you-go pricing. Workflow scheduling, as a typical NP-Complete problem, is one of the major issues in cloud computing. However, in the cloud scenario with unlimited resources, how to generate an efficient and economical workflow scheduling scheme under the deadline constraint is still an extraordinary challenge. In this article, we propose a hybrid heuristic algorithm called enhanced task type first algorithm (ET2FA) to solve deadline-constrained workflow scheduling in cloud with new features such as hibernation and per-second billing. The objectives to be minimized include the total cost and total idle rate. ET2FA involves three phases: 1) Task type first algorithm, which schedules tasks based on topological level and task types, and utilizes a compact-scheduling-condition based VM selection method to assign each task. 2) Delay operation based on block structure, which further optimizes total cost and total idle rate based on block structure properties. 3) Instance hibernate scheduling heuristic, which sets an instance to hibernate if idle for a duration. Extensive simulation experiments based on seven well-known real-world workflow applications show that ET2FA delivers better performance in comparison to the state-of-the-art algorithms.},
author = {Sun, Zaixing and Zhang, Boyu and Gu, Chonglin and Xie, Ruitao and Qian, Bin and Huang, Hejiao},
doi = {10.1109/TSC.2022.3196620},
issn = {19391374},
journal = {IEEE Transactions on Services Computing},
keywords = {Workflow scheduling,cloud computing,deadline constraint,directed acyclic graph,hibernate instance},
number = {3},
pages = {1807--1821},
title = {{ET2FA: A Hybrid Heuristic Algorithm for Deadline-Constrained Workflow Scheduling in Cloud}},
url = {https://ieeexplore.ieee.org/document/9851558/},
volume = {16},
year = {2023}
}`,

    'Sun2025-JOCO': `@article{Sun2025-JOCO,
abstract = {Cloud computing has a powerful capability to handle a large number of tasks. However, this capability comes with significant energy requirements. It is critical to overcome the challenge of minimizing energy consumption within cloud service platforms without compromising service quality. In this paper, we propose a heuristic energy-saving scheduling algorithm, called Real-time Multi-workflow Energy-efficient Scheduling (RMES), which aims to minimize the total energy consumption in a container-based cloud. RMES schedules tasks in the most parallelized way to improve the resource utilization of the running machines in the cluster, thus reducing the time of the global process and saving energy. This paper also considers the affinity constraints between containers and machines, and RMES has the ability to satisfy the resource quantity and performance requirements of containers during the scheduling process. We introduce a re-scheduling mechanism that automatically adjusts the scheduling decisions of remaining tasks to account for the dynamic system states over time. The results show that RMES outperforms other scheduling algorithms in energy consumption and success rate. In the higher arrival rate scenario, the proposed algorithm saves energy consumption by more than 19.42%. The RMES approach can enhance the reliability and efficiency of scheduling systems.},
author = {Sun, Zaixing and Huang, Hejiao and Li, Zhikai and Gu, Chonglin},
doi = {10.1007/s10878-025-01265-8},
isbn = {0123456789},
issn = {15732886},
journal = {Journal of Combinatorial Optimization},
keywords = {Container cloud,Energy minimization,Multi-workflow scheduling,Real time},
number = {2},
pages = {1----21},
publisher = {Springer US},
title = {{Energy-efficient real-time multi-workflow scheduling in container-based cloud}},
url = {https://doi.org/10.1007/s10878-025-01265-8},
volume = {49},
year = {2025}
}`,

    'Sun2024-ICIC': `@inproceedings{Sun2024-ICIC,
abstract = {With the rapid development of cloud computing, the issue of how to reduce energy consumption has attracted a great deal of attention. Especially for dynamic workflow scheduling, dependency constraints between tasks and high quality of service requirements, such as real-time requirements and deadline constraints, make it very challenging. This paper focuses on the energy-efficient scheduling problem, which jointly considers the impact of finer-grained tasks with CPU and memory configurations on energy consumption. A dynamic workflow scheduling simulator is developed to mimic the scheduling process in real-world scenarios. Then, we propose a Cooperative Coevolution Genetic Programming to learn heuristics for both the task selection decision and the instance selection decision, using the simulator for heuristic evaluation. The scheduling heuristics obtained by Cooperative Coevolution Genetic Programming evolution can then be used to make real-time decisions in dynamic environments. The simulation results show that the proposed method has managed to obtain better scheduling heuristics than the baseline methods in terms of energy consumption and resource utilization.},
author = {Sun, Zaixing and Zhang, Fangfang and Mei, Yi and Huang, Hejiao and Gu, Chonglin and Qian, Bin and Zhang, Mengjie},
booktitle = {Proceedings of the International Conference on Intelligent Computing},
doi = {10.1007/978-981-97-5578-3_14},
isbn = {9789819755776},
issn = {16113349},
keywords = {Cloud Computing,Dynamic Workflow Scheduling,Genetic Programming Hyper-heuristics},
pages = {169--182},
title = {{Evolving Scheduling Heuristics for Energy-Efficient Dynamic Workflow Scheduling in Cloud via Genetic Programming Hyper-Heuristics}},
volume = {14862 LNCS},
year = {2024}
}`,

    'Sun2023-COCOA': `@inproceedings{Sun2023-COCOA,
abstract = {Cloud computing has a powerful ability to handle a large number of tasks. Correspondingly, it also consumes a lot of energy. Reducing the energy consumption of cloud service platforms while ensuring the quality of service has become a crucial issue. In this paper, we propose a heuristic energy-saving scheduling algorithm named Real-time Multi-workflow Energy-efficient Scheduling (RMES) with the aim to minimize the total energy consumption in container cloud. RMES executes tasks as parallel as possible to enhance the resource utilization of the running machines in cluster, therefore reducing the time of the global process, saving energy as a result. RMES takes advantage of the affinity between containers and machines to meet the resource quantity and performance requirements of containers during scheduling. In order to follow the change of the system state overtime, we introduce the re-scheduling mechanism, which can automatically adjust the scheduling decisions of the tasks that have not yet been executed in the scheduling scheme. The experimental results show that RMES has obvious advantages over other scheduling algorithms in terms of energy consumption and success ratio.},
address = {Cham},
author = {Sun, Zaixing and Li, Zhikai and Gu, Chonglin and Huang, Hejiao},
booktitle = {Proceeding of 16th Annual International Conference on Combinatorial Optimization and Applications},
doi = {10.1007/978-3-031-49611-0_12},
editor = {Wu, Weili and Guo, Jianxiong},
isbn = {9783031496103},
issn = {16113349},
keywords = {Container cloud,Energy minimization,Multi-workflow scheduling,Real time},
pages = {168--181},
publisher = {Springer Nature Switzerland},
title = {{An Energy-Efficient Scheduling Method for Real-Time Multi-workflow in Container Cloud}},
url = {https://link.springer.com/10.1007/978-3-031-49611-0_12},
volume = {14461 LNCS},
year = {2024}
}`,

    'Sun2021-CLOUD': `@inproceedings{Sun2021-CLOUD,
abstract = {Workflow scheduling is one of the most challenging problems in cloud computing. This paper proposes a heuristic algorithm task type first algorithm (T2FA) for solving deadline-constrained workflow scheduling in cloud with multicore resource (DWS_CMR). The objectives to be minimized are the maximal completion time (i.e., makespan) and the total costs. Firstly, resource model and workflow application model are introduced. Resource model has the configurations of multicore, processing capacity, bandwidth and leasing price, and workflow application model is described by directed acyclic graph (DAG). Based on above models, the mathematical model of DWS-CMR is established, which allows multiple tasks to run concurrently on multicore resources. Secondly, to exploit the characteristics of the problem, the structures of DAG are decomposed and formulated. Merging tasks conforming to the first structure into task blocks can simplify DAG. Four special types of tasks are extracted from the second and third structures, and are preferentially scheduled in task scheduling stage. Then, a new interrelated calculation method of estimated start time and actual start time of tasks is proposed, which can complete the task-To-resource mapping. Finally, T2FA is devised, which incorporates two important phases, including pre-processing and task scheduling. Experimental results show that T2FA can achieve significantly better schedules in most test cases compared to several existing algorithms.},
author = {Sun, Zaixing and Gu, Chonglin and Huang, Hejiao and Zhang, Honglin},
booktitle = {Proceeding of 2021 IEEE 14th International Conference on Cloud Computing (CLOUD)},
doi = {10.1109/CLOUD53861.2021.00048},
isbn = {978-1-6654-0060-2},
issn = {21596190},
keywords = {Cloud Computing,Deadline Constraint,Directed Acyclic Graph,Multicore Resource,Workflow Scheduling},
mendeley-groups = {bib},
month = {sep},
pages = {345--354},
publisher = {IEEE},
title = {{T2FA: A Heuristic Algorithm for Deadline-Constrained Workflow Scheduling in Cloud with Multicore Resource}},
url = {https://ieeexplore.ieee.org/document/9582237/},
year = {2021}
}`,

    'Sun2025-TSC': `@article{Sun2025-TSC,
abstract = {Cloud-Fog computing has emerged as an essential paradigm to support the growing demand for real-time data processing driven by the Internet of Things. By integrating the extensive computing capabilities of cloud data centres with the low-latency benefits of fog nodes, this architecture increases resource utilisation and improves quality of service. However, the dynamic and heterogeneous nature of cloud fog environments poses significant workflow scheduling challenges, especially when optimising multiple trade-offs such as latency, cost, energy consumption, and resource utilisation. This paper investigates the many-objective dynamic workflow scheduling problem under deadline constraints in container-based cloud-fog computing environments (MDWS-CoCF). Unlike existing studies that primarily focus on horizontal scaling, this work considers both vertical and horizontal scaling of containers, allowing for real-time adjustments of container configurations based on task-specific requirements. To address this complex problem, we first develop a dynamic workflow scheduling simulator that models real-world scenarios, including a variety of task categories and container scalability. Based on this simulator, we propose a Cooperative Coevolution Genetic Programming (CCGP) approach that evolves specialised heuristics for task selection, resource allocation, and container deployment to facilitate adaptive and efficient scheduling in MDWS-CoCF. Extensive simulations using real-world data traces show that the proposed CCGP approach significantly outperforms existing baseline algorithms, achieving superior performance as measured by the HyperVolume and Inverted Generational Distance metrics. The results show that the evolved heuristics are robust and effective under different dynamic scenarios, ensuring balanced optimisation of many objectives.},
author = {Sun, Zaixing and Zhang, Fangfang and Mei, Yi and Huang, Hejiao and Gu, Chonglin and Wang, Bin and Zhang, Mengjie},
doi = {10.1109/TSC.2025.3636121},
isbn = {1211173609009},
issn = {1939-1374},
journal = {IEEE Transactions on Services Computing},
keywords = {Cloud computing,dynamic many-objective optimisation,elastic scaling,fog computing,genetic programming hyper-heuristic,workflow scheduling},
month = {jan},
number = {1},
pages = {225--239},
publisher = {IEEE},
title = {{Cooperative Coevolution Genetic Programming for Dynamic Joint Workflow Scheduling and Container Scaling in Cloud-Fog Computing}},
url = {https://ieeexplore.ieee.org/document/11267070/},
volume = {19},
year = {2026}
}`,

    'Sun2026-INFOCOM': `@@inproceedings{Sun2026-INFOCOM,
author = {Sun, Zaixing and Zhang, Liang and Tang, Quan and Jiang, Jun and Gu, Chonglin and Wang, Bin},
booktitle = {IEEE Conf. Comput. Commun. Work. INFOCOM WKSHPS 2026},
file = {:Users/zaixing/Github/Mendeley Desktop/IEEE Conference on Computer Communications Workshops, INFOCOM WKSHPS 2026/Sun et al.. 2026. Multitask Cooperative Genetic Programming for Co-Scheduling Online-Offline Workflows in the Cloud.pdf:pdf},
isbn = {2024121117360},
pages = {1--6},
title = {{Multitask Cooperative Genetic Programming for Co-Scheduling Online-Offline Workflows in the Cloud}},
year = {2026}
}`,


}