# ci name
# ci 脚本名称
name: Deploy Jekyll site to public github repos

on:
  # Runs on pushes targeting the default branch
  # 当代码 push 到 main 分支时, 执行该脚本
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  # 允许你 手动执行 这个脚本
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# GITHUB_TOKEN 的操作权限
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# job 执行任务, 可以有多个, 默认并行运行, 可以通过 needs 关键字来设置依赖的其他 jobs
# step : 任务下的执行步骤, 一个job 会有多个步骤
# 操作:  一个step 下可以执行多个操作, 通常一行脚本为一个操作
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # false 是用 personal token，true 是使用 GitHub token
          fetch-depth: 0


      - name: Commit and Push
        working-directory: <work-dir>
        run: |
          git init
          git checkout -b gh-pages
          git add -A
          git -c user.name='zaixing-sun' -c user.email='zaixing.sun@micc.hitsz.edu.cn' commit -m '<message>' 
          git remote add origin https://${{secrets.HOMEPAGE_ACCESS_TOKEN}}@github.com/zaixing-sun/zaixing-sun.github.io.git
          git push origin gh-pages -f -q

      # - name: 部署_site到博客网站仓库
      #   working-directory: ./_site
      #   run: |
      #     git init
      #     git checkout -b main
      #     git add -A
      #     git -c user.name='zaixing-sun' -c user.email='zaixing.sun@micc.hitsz.edu.cn' commit -m 'anything' 
      #     git push "https://${ { github.actor } }:${ { secrets.HOMEPAGE_ACCESS_TOKEN } }@github.com/zaixing-sun.github.io" HEAD:main -f -q




# # Sample workflow for building and deploying a Jekyll site to GitHub Pages
# name: Deploy Jekyll with GitHub Pages dependencies preinstalled

# on:
#   # Runs on pushes targeting the default branch
#   push:
#     branches: ["main"]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# permissions:
#   contents: read
#   pages: write
#   id-token: write

# # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
# concurrency:
#   group: "pages"
#   cancel-in-progress: false

# jobs:
#   # Build job
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Setup Pages
#         uses: actions/configure-pages@v5
#       - name: Build with Jekyll
#         uses: actions/jekyll-build-pages@v1
#         with:
#           source: ./
#           destination: ./_site
#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3

#   # Deployment job
#   deploy:
#     environment:
#       name: github-pages
#       url: ${{ steps.deployment.outputs.page_url }}
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v4
